name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          check-latest: true
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - name: Check can publish
        id: can_publish
        run: npx can-npm-publish --verbose
      - name: Install modules
        run: npm ci
      - name: Run unit test
        run: npm test
      - name: Build
        run: npm run build
      - name: Publish npm module
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: No Update
        if: failure() && steps.can_publish.outcome == 'failure'
        run: echo "No Update"
